---
title: "Untitled"
output: html_document
date: "2024-12-28"
---

```{r}
library(readxl)
library(tidyverse)
library(dplyr)

getwd()
setwd('/Users/daniilefremov/Desktop/dataR/QCA')
dfSE = data.table(get(load("196slers1967to2016_20180908.RData")))

dfSE = dfSE %>% filter(!(dname == "" & is.na(dno)))
parf = c(unique(dfSE$partyz)[c(2:4,6:7)])
dfSE$dno = paste(as.character(dfSE$dno), dfSE$dname, sep = "_")

dfSEH1 = dfSE %>% filter(etype == "g" & sen == 0, dtype == 1) %>% select(year, sab, dno, partyz, vote, cand) %>% group_by(year, sab, dno) %>% filter(!any(partyz %in% parf) & all(c("d", "r") %in% partyz))  %>% ungroup() %>% group_by(year, sab, dno, partyz) %>% filter(n() == 1) %>% select(1:5)

dfSEH2 = dfSE %>% filter(etype == "g" & sen == 0, dtype == 1) %>% select(year, sab, dno, partyz, vote, cand) %>% group_by(year, sab, dno) %>% filter(!any(partyz %in% parf) & all(c("d", "r") %in% partyz))  %>% ungroup() %>% group_by(year, sab, dno, partyz) %>% group_by(year, sab, dno, partyz) %>% filter(n() > 1) %>% ungroup() %>% group_by(year, sab, dno, partyz, cand)  %>% reframe(vote = sum(vote)) %>% select(1:4,6)

dfSEH3 = rbind.data.frame(dfSEH1,dfSEH2)

electypeH = dfSEH3 %>% pivot_wider(names_from = partyz, values_from = c(vote), values_fn = first) %>% mutate(year = case_when((year %% 2 == 1) ~ year+1,  .default = year))
```

```{r}
safeSTHr = electypeH %>% mutate(perc = (r/(r+d)*100)) %>% group_by(year, sab) %>% mutate(avg = mean(perc, na.rm = TRUE)) %>% filter(perc - 50 >= 5) %>% reframe(nsafeH = n())

safeSTHd = electypeH %>% mutate(perc = (d/(r+d)*100)) %>% group_by(year, sab) %>% mutate(avg = mean(perc, na.rm = TRUE)) %>% filter(perc - 50 >= 5) %>% reframe(nsafeH = n())

Housesafe = rbind.data.frame(safeSTHr, safeSTHd) %>% group_by(year, sab) %>% reframe(nsafeH = sum(nsafeH))
```

```{r}
ff = function(x, y){dfSE %>% filter(etype == "g" & sen == x, dtype == 1) %>% select(year, sab, dno, partyz, vote, cand) %>% group_by(year, sab, dno) %>% filter(!any(partyz %in% y))  %>% ungroup() %>% group_by(year, sab, dno) %>% filter(n() == 1) %>% select(1:5) %>% ungroup()}

parfd = c(unique(dfSE$partyz)[c(2:7)])
parfr = c(unique(dfSE$partyz)[c(1:4,6:7)])

unHR = ff(0, parfr) %>% mutate(year = if_else(year %% 2 == 1, year+1, year)) %>%  group_by(year, sab) %>% reframe(N = n())

unHD = ff(0, parfd) %>% mutate(year = if_else(year %% 2 == 1, year+1, year)) %>%  group_by(year, sab) %>% reframe(N = n())

unH = rbind.data.frame(unHR, unHD) %>% group_by(year, sab) %>% reframe(NH = sum(N))
```

```{r}
dfHN = dfSE%>% filter(etype == "g" & sen == 0, dtype == 1) %>% select(year, sab, dno)  %>% distinct() %>% group_by(year, sab) %>% reframe(NG = n()) %>% mutate(year = case_when((year %% 2 == 1) ~ year+1,  .default = year)) %>% filter(!sab %in% c("az","id","md","nh","nj","nd","sd","vt","wv", "al", "ms"))

dfHN = left_join(dfHN, Housesafe, by = c("year","sab"))
dfHN = dfHN %>%  mutate(nsafeH = ifelse(is.na(nsafeH), 0, nsafeH))
dfHN = left_join(dfHN, unH, by = c("year","sab")) 
dfHN = dfHN %>%  mutate(NH = ifelse(is.na(NH), 0, NH))
dfHN = dfHN %>% mutate(NGs = NH + nsafeH)
dfHN = dfHN %>% mutate(NProp = (NGs/NG)*100) %>% select(1:3, 7)
```


```{r}
#write.xlsx(dfHN, "House_st_districts.xlsx")
```